apiVersion: apps/v1
kind: Deployment
metadata:
  name: tire-testing
spec:
  template:
    spec:
      containers:
        - name: tire-testing
          image: 685368365467.dkr.ecr.eu-central-1.amazonaws.com/tire-testing-gitops-snapshot:2026.07.13-5
          env:
            - name: DB_URL
              value: "jdbc:postgresql://<gitops-db-private-ip>:5432/tire_testing_gitops_staging"